name       : python3-jedi
version    : 0.15.1
release    : 10
source     :
    - git|https://github.com/davidhalter/jedi.git : v0.15.1
license    : MIT
component  : programming.python
summary    : An autocompletion tool for Python that can be used for text editors.
description: |
    An autocompletion tool for Python that can be used for text editors.
builddeps  :
    - python-parso
    - python-pytest
rundeps    :
    - python-parso
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    ln -sv jedi.git $workdir/../jedi
    %python3_test pytest3 -v
